apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
spec:
  provider:
    azurekv:
      # Azure Workload Identity auth allows ESO to auth to Key Vault
      # without storing Azure Client IDs/Secrets in Kubernetes
      authType: WorkloadIdentity
      vaultUrl: "https://my-company-prod-kv.vault.azure.net"
      serviceAccountRef:
        name: external-secrets-sa
        namespace: external-secrets
