apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: backend-api
spec:
  # The frequency that ESO checks Azure Key Vault for changes (Secret Rotation)
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: db-secret-k8s # The name of the native K8s secret to generate
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: backend-postgres-password
